# Generated by Django 3.0.8 on 2020-07-29 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('assignment', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='application_pics')),
                ('registrations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField()),
                ('green', models.PositiveSmallIntegerField()),
                ('blue', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('application_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_register.ApplicationTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_register.Question')),
            ],
        ),
        migrations.AddField(
            model_name='applicationtemplate',
            name='background_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_register.Color'),
        ),
        migrations.AddField(
            model_name='applicationtemplate',
            name='category_tags',
            field=models.ManyToManyField(to='volunteer_register.CategoryTag'),
        ),
        migrations.CreateModel(
            name='ApplicationSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('application_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_register.ApplicationTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('application_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_register.ApplicationSubmission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer_register.Question')),
            ],
        ),
    ]
