# Generated by Django 3.0.8 on 2020-07-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtemplate',
            name='organization',
            field=models.CharField(default='Volley Nonprofit', max_length=50),
            preserve_default=False,
        ),
    ]
