# Generated by Django 3.0.8 on 2020-08-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_register', '0002_auto_20200729_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtemplate',
            name='job_description',
            field=models.TextField(default='Job Descripton Area'),
            preserve_default=False,
        ),
    ]
