# Generated by Django 3.0.8 on 2020-08-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_register', '0004_auto_20200805_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='menu_name',
            new_name='display_name',
        ),
    ]
